import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Layout from "@/components/Layout";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./authContext/contaxt";

export const metadata: Metadata = {
  title: "Shopping-ecommerce-App",
  description: "Generated by create shopping  app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider>
          <Layout>
            <Header></Header>
            {children}
            <Footer></Footer>
            <Toaster />
          </Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
